//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pagina_Agripac
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cabecera_Nomina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cabecera_Nomina()
        {
            this.DETALLE_NOMINA = new HashSet<DETALLE_NOMINA>();
        }
    
        public int id_Nomina { get; set; }
        public string Comprobante { get; set; }
        public int id_empleado { get; set; }
        public int idSueldo { get; set; }
        public Nullable<double> Iess_por { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Periodo { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Sueldo Sueldo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_NOMINA> DETALLE_NOMINA { get; set; }
    }
}
