//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pagina_Agripac
{
    using System;
    using System.Collections.Generic;
    
    public partial class Det_Asistencia
    {
        public int id_det_asistencia { get; set; }
        public int id_asistencia { get; set; }
        public string Mes_Completo { get; set; }
        public Nullable<int> Dias_Inasistidos { get; set; }
    
        public virtual Reporte_Asistencia Reporte_Asistencia { get; set; }
    }
}
