//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pagina_Agripac
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AgripacEntities : DbContext
    {
        public AgripacEntities()
            : base("name=AgripacEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cabecera_Nomina> Cabecera_Nomina { get; set; }
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Det_Asistencia> Det_Asistencia { get; set; }
        public virtual DbSet<Det_Horario> Det_Horario { get; set; }
        public virtual DbSet<Det_Utilidades> Det_Utilidades { get; set; }
        public virtual DbSet<DETALLE_NOMINA> DETALLE_NOMINA { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Horario> Horario { get; set; }
        public virtual DbSet<Jornada> Jornada { get; set; }
        public virtual DbSet<Motivo_Asistencia> Motivo_Asistencia { get; set; }
        public virtual DbSet<Reporte_Asistencia> Reporte_Asistencia { get; set; }
        public virtual DbSet<Sueldo> Sueldo { get; set; }
        public virtual DbSet<Utilidades> Utilidades { get; set; }
    }
}
